### PR TITLE
Feature(alert toast animation)

### PR DESCRIPTION
**Pull request by lzhuor**
Added fade-in and slide-left when an alert (`<Toast />`) is displayed. 
Added fade-out and slide-right when an alert (`<Toast />`) is closed.

**Blocker**: Snapshots update is **blocked** by https://github.com/blockchain/components/issues/252
Enzyme shallow render is not working due to explicit version declaration of `react: "16.7.0"` in `@blockchain-com/components`. It blocks Enzyme shallow render with Hooks.

## Ticket Number
WEB4-

## Description (optional)
Added fade-in and fade-out animation of alert toast

## Testing Steps (optional)
Dispatch an action (e.g. `actions.alert.displaySuccess("Hello World!")`) or check out `Toasts` in storybook with `yarn storybook:serve`.

### CODE REVIEW

**Comment by plondon** [comment]
Hey John, is this the same work @jjBlockchain is doing?

**Comment by plondon** [comment]
@jjBlockchain can you test this out and let me know if we want to go with this approach instead?

**Comment by jjBlockchain** [comment]
@plondon yea, ill test it and let you know

**Comment by schnogz** [comment]
The React dependency issue was actually deep inside of `@storybook`.  Since we will be abandoning this component library in favor of `@blockchain/components` in the future, deleting the `toast.spec` was easiest solution.

@jjBlockchain I closed your other PR's and cherry-pick'd your persist commit into this branch.  

@lzhuor & @jjBlockchain  can you both review the latest changes and make sure everything looks good.

**Comment by lzhuor** [comment]
Thank you @schnogz @jjBlockchain . LGTM.

**Pull request merged**
