### PR TITLE
chore(dynamic-routing): remove dynamic routing and only use threshold

### PR DESCRIPTION
**Pull request by jjBlockchain**
## Description (optional)
* remove dynamic routing and only use threshold

### CODE REVIEW

**Review by CTucker-BC — APPROVED** [review]

**Comment by Sentini14** [comment]
Do you mean I can Withdraw  please? How can I?

***@***.***

**Comment by CTucker-BC** [comment]
> Do you mean I can Withdraw please? How can I? ***@***.***

This is not the appropriate place for support, please contact support if you're having issues at https://support.blockchain.com/hc/en-us  

Thank you.

**Comment by Sentini14** [comment]
Yes, please!

**Comment by sstephanou-bc** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [3644e07f\-20b3\-4c58\-a116\-51477821413d](https://eu.ast.checkmarx.net/projects/f3c879d8-da6e-4aaa-aeee-f377cc306d79/scans?id=3644e07f-20b3-4c58-a116-51477821413d&branch=chore%2Fdynamic-routing)
### No New Or Fixed Issues Found

**Pull request merged**
