### PR TITLE
fix(clang): add domain to setting clang cookie

### PR DESCRIPTION
**Pull request by jjBlockchain**
## Description (optional)
Add a concise explanation of the changes.

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

### CODE REVIEW

**Review by CTucker-BC — APPROVED** [review]

**Comment by Sentini14** [comment]
I need my private key pharse

***@***.***

**Comment by Sentini14** [comment]
H

Hello 👋 I need your help

**Comment by sstephanou-bc** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [eb43a436\-54e2\-44f8\-98ea\-75ded3c3d1ff](https://eu.ast.checkmarx.net/projects/f3c879d8-da6e-4aaa-aeee-f377cc306d79/scans?id=eb43a436-54e2-44f8-98ea-75ded3c3d1ff&branch=fix%2Fclang)
### No New Or Fixed Issues Found

**Comment by Sentini14** [comment]
Great!

**Comment by raventechictsolution** [comment]
harsh value####2912$$$$)^**0688
Adamuibrahim13@Aol.com/

**Pull request merged**
