### PR TITLE
Sfox details

### PR DESCRIPTION
**Pull request by prwelber**
PR mainly focused on small fixes for SFOX signup flow, including a redesigned create step (edit functionality not yet working for verified emails/mobiles), handling when a user isn't in a supported country for partner select, and some fixes for Link and Verify step.

### CODE REVIEW

**Comment by prwelber** [comment]
This PR also bumps the React version to 16.3

**Comment by plondon** [comment]
Can you also fix the issue caused by: http://github.com/blockchain/blockchain-wallet-v4-frontend/blob/13d387258e0580c0332fa5c7d6e587d043598839/packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Link/BankAccounts.js#L39

**Comment by plondon** [comment]
screen shot 2018-04-03 at 10 50 08 am

Needs a little <3

**Comment by prwelber** [comment]
@plondon the bank link error should be fixed with this PR. it works for me now, does it not for you?

**Pull request merged**
