### PR TITLE
Migrate to release-it v11

### PR DESCRIPTION
**Pull request by webpro**
## Description

Update release-it + config to v11.

Note that the `changelog` executable in the `git._changelog` option is not there. Not sure what package is needed for this. You can fix this and remove the underscore from `_changelog`.

## Change Type

Releases

## Testing Steps

`npm run release`

## Code Checklist

- [x] Code compiles successfully (verified via `yarn start`)
- [x] `README.md` and other documentation is updated as needed

### CODE REVIEW

**Comment by plondon** [comment]
@webpro did you just update a dependency for us? #triggered

❤️

**Comment by webpro** [comment]
I think I did :)

**Comment by plondon** [comment]
Hmm @webpro, getting v{version} in the commit message:

commit 2e05129c7e31bc9c6abc0fbcd23ad1207435135d (HEAD -> dependency-update)
Author: plondon <philip@blockchain.com>
Date:   Fri May 3 12:37:13 2019 -0400

    chore(Release): v{version}

**Comment by webpro** [comment]
Oops, I replaced the `%s` incorrectly 🙈

**Pull request merged**
