### PR TITLE
upgrade - npm => yarn, lerna bootstrap => yarn workspaces

### PR DESCRIPTION
**Pull request by tony-blockchain**
## Description
Yarn is faster at building than npm/lerna

However there's no clean way yet to run command in every package using yarn workspaces.
There's https://github.com/whoeverest/wsrun but I wouldn't trust such that such package cannot introduce a vulnerability compared to yarn/lerna (lerna also shouldn't be blindly trusted ofc)
So for now I'd keep lerna for the sole purpose of running task among every package.

To install packages run `yarn` in root. To add module do a `cd packages/package-name` and `yarn add module-name` 

## Change Type
- Upgrades

## Testing Steps
Test commands you usually use.
I've tested build/start/test

## Code Checklist
- [ ] Code compiles successfully (verified via `yarn start`)
- [ ] No lint issues exist (verified via `yarn lint`)
- [ ] New and existing unit tests pass (verified via `yarn test`)
- [ ] `README.md` and other documentation is updated as needed

### CODE REVIEW

**Comment by plondon** [comment]
> So for now I'd keep lerna for the sole purpose of running task among every package.

But this PR removes it

**Comment by tony-blockchain** [comment]
lerna remains to launch jobs in every package, I now think that it's better to replace it by manual calling each package

**Comment by schnogz** [comment]
If we wait until the components package is busted out to its own repo, we shouldn't need Lerna to run commands. Just manually calling the two remaining packages wont be too bad. Let's leave this PR open until that happens.

**Comment by tony-blockchain** [comment]
@schnogz it isn't any worse just calling 3 packages manually right. Amount of packages won't increase anyway and the repo split's not a quick thing, so I guess I wipe lerna config and ci install script, change a couple of scripts and we're good to go.

**Comment by tony-blockchain** [comment]
checked `wsrun` with `snyk` and looked over the code myself, looks safe.
from now on it's fully yarn, nothing else involved

**Comment by schnogz** [comment]
This PR will address issue #710 !

**Pull request merged**
