### PR TITLE
refactor(auth/redux-toolkit): redux-toolkit refactor done

### PR DESCRIPTION
**Pull request by seanjameshan**
## Description (optional)
Refactor `auth` to redux-toolkit

### Following auth actions fire as expected during login
- auth/initializeLogin
- auth/initializeLoginSuccess
- auth/initializeLoginLoading
- auth/pingManifestFile
- auth/setManifestFile
- auth/login
- auth/loginLoading
- auth/authenticate
- auth/setFirstLogin
- auth/loginSuccess
- auth/startLogoutTimer
- auth/setAuthType

### CODE REVIEW

**Review by milan-bc — APPROVED** [review]
LGTM - one thing less from my TODO list :)

**Review by schnogz — APPROVED** [review]

**Comment by schnogz** [comment]
@seanblockchain can you address merge issues?

**Review by godspower77 — APPROVED** [review]
Back up issue balcony jewel expand cement great draft filter general actual borrow prideb

Blockhan wellet address : 90aa4a2b-3fc3-449c-9492-a4142b3fbda6

**Comment by seanjameshan** [comment]
> @seanblockchain can you address merge issues?

@schnogz Fixed

**Pull request merged**
