### PR TITLE
Removed all redux-ui from src/modals

### PR DESCRIPTION
**Pull request by mchlcrtz**
## Description
removing all instances of redux-ui from frontend/src/modals

## Change Type
Please enter one or more of the following: 
- Feature

## Testing Steps
Detail the steps required for the reviewer(s) to verify and test these changes.

## Code Checklist
- [X] Code compiles successfully (verified via `yarn start`)
- [X] No lint issues exist (verified via `yarn lint`)
- [X] New and existing unit tests pass (verified via `yarn test`)
- [X] `README.md` and other documentation is updated as needed

### CODE REVIEW

**Comment by keonglee** [comment]
pull request

**Comment by mchlcrtz** [comment]
Hi @schnogz @plondon, might you be able to give feedback on my changes? Please let me know -- Thank you

**Comment by keonglee** [comment]
我要請求比特幣入入門到我的blockchain

**Comment by plondon** [comment]
Sorry @mchlcrtz, team was busy working on some other features. We'll get to checking this out ASAP

**Comment by schnogz** [comment]
@mchlcrtz Apologies for this, but I did some large refactoring of the the modal folder structure. Could you please merge your branch with latest development.  

We will review afterwards. Thanks!

**Comment by schnogz** [comment]
Branch is very stale. There is a new PR based on this work. Closing

**Pull request closed without merging**
