### PR TITLE
Milan/wal 101 auth new public background screen

### PR DESCRIPTION
**Pull request by milan-bc**
## Description (optional)
this PR  include recent changes we did on login page + updated from development branch; once when we do update `secure-channel-login` this PR will have less changes.

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

### CODE REVIEW

**Review by schnogz — CHANGES_REQUESTED** [review]
Can you fix the commit history here?  Maybe make a new branch off development and cherrypick your commits

**Comment by milan-bc** [comment]
@schnogz yeah first have to update base branch with dev, then this will looks way better

**Comment by milan-bc** [comment]
@schnogz here https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/2676

**Comment by milan-bc** [comment]
Closing this because we have a #2676

**Pull request closed without merging**
