### PR TITLE
Fix/remove unused getSpendableActiveAddresses

### LINKED ISSUE #1004: Remove `Wallet.getSpendableActiveAddresses` related code
## Description
It seems no more `getSpendableActiveAddresses` definition in `Wallet` type. Shall we remove its related code?

For example:
 - In `redux/payment/btc/saga.js`
```javascript
const calculateFrom = function*(origin, network) {
   ...
    // No origin => assume origin = all the legacy addresses (non - watchOnly)
    if (isNil(origin) || origin === '') {
      let spendableActiveAddresses = yield select(
        S.wallet.getSpendableActiveAddresses
      )
      return fromLegacyList(spendableActiveAddresses)
    }
   ...
  }
```

- In selector(s):
```javascript
export const getSpendableActiveAddresses = compose(
  Wallet.getSpendableActiveAddresses,
  getWallet
)
```

### PR DESCRIPTION
**Pull request by lzhuor**
Fixes #1004 It seems we don't need this function anymore. 

## Change Type
Please enter one or more of the following: 
- Technical Debt

## Testing Steps
Not Applicable as this code chunk is not executed.

## Code Checklist
- [x] Code compiles successfully (verified via `yarn start`)
- [x] No lint issues exist (verified via `yarn lint`)
- [x] New and existing unit tests pass (verified via `yarn test`)
- [x] `README.md` and other documentation is updated as needed

### CODE REVIEW

**Comment by plondon** [comment]
@jtormey do you have any insight into when calculateFrom, origins, could be nil or ''?

**Comment by plondon** [comment]
@lzhuor lot's of changes were just merged, suggest you update your local env.

**Comment by plondon** [comment]
Let me know if you have any questions

**Comment by lzhuor** [comment]
Thank you, @plondon. Updated.

**Comment by schnogz** [comment]
did we ever hear back from @jtormey on this?

**Comment by jtormey** [comment]
I'm not sure when we might hit those cases, sorry 😕

**Comment by plondon** [comment]
@jtormey the old transfer all feature?

**Comment by jtormey** [comment]
Ah, yeah, possibly. Or the export history feature for all spendable actives.

**Comment by plondon** [comment]
Since we might want this in the future closing for now

**Pull request closed without merging**
