### PR TITLE
Fix/bch export

### PR DESCRIPTION
**Pull request by prwelber**
## Description
1307

## Change Type
Please enter one or more of the following: 
- Bug Fix

## Testing Steps
Detail the steps required for the reviewer(s) to verify and test these changes.

## Code Checklist
- [ ] Code compiles successfully (verified via `yarn start`)
- [ ] No lint issues exist (verified via `yarn lint`)
- [ ] New and existing unit tests pass (verified via `yarn test`)
- [ ] `README.md` and other documentation is updated as needed

### CODE REVIEW

**Comment by prwelber** [comment]
TODO

- [ ] fix issue where selecting a BCH imported address in the tx list returns an error from `/multiaddr`

**Comment by plondon** [comment]
Was this ever working @TheLeoB?

If yes would rather fix the root cause than patch a fix.

**Comment by TheLeoB** [comment]
@plondon I feel like this is something we could have caught with testing, but I can't say for sure. Is there a way for us to look at builds older than 4.2.1?

**Comment by plondon** [comment]
release/v4.1.x branch is still available

**Comment by TheLeoB** [comment]
That branch runs 4.2.1

**Comment by plondon** [comment]
Here is the commit hash for 4.0.6 87ac43f8488b37c345f46479497e73d1b9ca0162

So `git co master` then `git reset 87ac43f8488b37c345f46479497e73d1b9ca0162` should bring you back there, then reset master to the latest

**Pull request merged**
