### PR TITLE
feat/delete-legacy: removed html files

### PR DESCRIPTION
**Pull request by jhagerman-bc**
## Description (optional)
Add a concise explanation of the changes.

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

### CODE REVIEW

**Comment by sstephanou-bc** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [870a655b\-02c4\-46b2\-b494\-27ba6643b486](https://eu.ast.checkmarx.net/projects/f3c879d8-da6e-4aaa-aeee-f377cc306d79/scans?id=870a655b-02c4-46b2-b494-27ba6643b486&branch=feat%2Fdelete-legacy)
### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
LOW|[Client_Hardcoded_Domain](https://eu.ast.checkmarx.net/results/f3c879d8-da6e-4aaa-aeee-f377cc306d79/870a655b-02c4-46b2-b494-27ba6643b486/sast/description/829/3455652598283285801)|/legacy\-pages/import\-wallet\.html: [31](https://github.com/blockchain/blockchain-wallet-v4-frontend/blob/feat/delete-legacy//legacy-pages/import-wallet.html#L31)

**Review by mperdomo-bc — APPROVED** [review]

**Review by walker112171 — COMMENTED** [review]
Y

**Review by walker112171 — COMMENTED** [review]
Don't really know what the reviews about

**Comment by Tangee69** [comment]
- - [ ] Ty[]()****

**Pull request merged**
