### PR TITLE
respect invited field in settings

### PR DESCRIPTION
**Pull request by salomegeo**
## Description
954

## Change Type
- Bug Fix

## Testing Steps
Use v2 wallet to log in.

## Code Checklist
- [ ] Code compiles successfully (verified via `yarn start`)
- [ ] No lint issues exist (verified via `yarn lint`)
- [ ] New and existing unit tests pass (verified via `yarn test`)
- [ ] `README.md` and other documentation is updated as needed

### CODE REVIEW

**Comment by salomegeo** [comment]
I'm not sure this is the way to go, do we even need this invited field? is it written somewhere else in v2-settings? if so upgrade could read it from there and put it in the settings.

**Comment by plondon** [comment]
We need it to roll out partnerships. It should be in get-info, not sure why not if its after you upgrade though.

**Comment by plondon** [comment]
Same issue in v3

**Comment by plondon** [comment]
Just added a note to self.

**Pull request merged**
