### PR TITLE
feat(nft-erc20-payments): Refactored atomicMatch, added new ERC20 fun…

### PR DESCRIPTION
**Pull request by jmichel-bc**
…ctions, working for ETH payments)

## Description (optional)
ERC20 payments not fully tested yet, will continue to work on this once auctions are working.

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

### CODE REVIEW

**Comment by Raydp** [comment]
Ragt tlh

**Review by Raydp — APPROVED** [review]

**Review by Donone19 — APPROVED** [review]

**Comment by Donone19** [comment]
I like to see the out come to it all good work.

**Comment by Raydp** [comment]
Rhfkn

**Comment by Raydp** [comment]
Randolph

**Review by Raydp — APPROVED** [review]

**Review by plondon — APPROVED** [review]

**Pull request merged**
