### PR TITLE
feat(settings): fixed header to be fixed, alignment of icons and proper copy has been placed

### PR DESCRIPTION
**Pull request by milan-bc**
## Description (optional)
This PR solved 
- alignment issue with icons
- fixed header on scroll
- fixed copy text

## Testing Steps (optional)
Login to wallet, click on settings gear and then on Trading Limits scrollable section
image

### CODE REVIEW

**Comment by pedroapfilho** [comment]
Screen Shot 2021-02-18 at 11 43 26 AM

Wouldn't it be better if we align these icons like this? With the same width, and same spacing

**Comment by milan-bc** [comment]
@pedroapfilho yeah might be, but designers made it like this from some reason, I do believe them :D

**Comment by hanabi62513** [comment]
No English

2021年2月18日(木) 23:45 Pedro Filho <notifications@github.com>:

**Comment by schnogz** [comment]
Yeah I think the alignment is fine for now.

**Review by schnogz — APPROVED** [review]

**Pull request merged**
