### PR TITLE
Fix/fix eslint and typo

### PR DESCRIPTION
**Pull request by lzhuor**
## Description
Fixed minor eslint errors and a typo

## Change Type
- Others (Linting and Docs)
1. `badges.js`: fixed indention
2. `config.js` & `addon.js`: Removed semi-column termination
3. `Development.md`: "accross" -> "across"

## Testing Steps
N.A.

## Code Checklist
- [x] Code compiles successfully (verified via `yarn start`)
- [x] No lint issues exist (verified via `yarn lint`)
- [x] New and existing unit tests pass (verified via `yarn test`)
- [x] `README.md` and other documentation is updated as needed

### CODE REVIEW

**Comment by schnogz** [comment]
Sorry about that @lzhuor, there was a CircleCI setting that was not enabled that would have allowed builds from forked repositories. I have since enabled it.

**Comment by lzhuor** [comment]
Thank you so much @schnogz for help! 

I can see it's triggered. However, I am getting below error:
```
#!/bin/bash -eo pipefail
npm install yarn babel-cli rimraf cross-env && yarn
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "react-intl-translations-manager@5.0.3": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2018-07-15T19_28_24_863Z-debug.log
Exited with code 1
```

Could you please advise what shall I check to resolve it? Locally it works so I suspect it's related to the local cache on circleci.

**Comment by tony-blockchain** [comment]
@lzhuor looks like Andrew just fixed it in https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/779/files feel free to rebase on it

**Comment by lzhuor** [comment]
❤️ Thank @tony-blockchain and @schnogz for help! 

Unfortunately, I still see ci/circleci: unit_tests failed due to timeout error. `yarn ci:test` works perfectly on my local machine.

I see the team is currently making some changes (#779 & #785 ) on circleci so I will defer this PR a bit 😆

**Pull request merged**
